import { cleanupStaleAvatars, getAvatarSignedUrl, removeAvatar, replaceAvatar } from './avatar-repository';
const user='07030000-0000-4000-8000-000000000001',avatar='07030000-0000-4000-8000-000000000002';
const old='07030000-0000-4000-8000-000000000003';
function client(updateError:unknown=null,removeError:unknown=null){const upload=jest.fn(async()=>({error:null}));const remove=jest.fn(async()=>({error:removeError}));const createSignedUrl=jest.fn(async()=>({data:{signedUrl:'https://signed.example/avatar'},error:null}));const rpc=jest.fn(async(name:string)=>name==='replace_avatar'?{data:updateError?null:{outcome:'updated'},error:updateError}:name==='list_avatar_cleanup'?{data:[{storage_path:`${user}/${old}.jpg`}],error:null}:{data:null,error:null});return{value:{storage:{from:()=>({upload,remove,createSignedUrl})},rpc},remove,rpc,createSignedUrl};}
beforeEach(()=>{globalThis.fetch=jest.fn(async()=>({arrayBuffer:async()=>new Uint8Array([1,2]).buffer})) as never;});
test('SQ-0703 replaces privately and deletes the prior owner object',async()=>{const c=client();await expect(replaceAvatar(c.value as never,{userId:user,avatarId:avatar,asset:{uri:'file://a',mimeType:'image/jpeg',byteSize:2,width:10,height:10},previousPath:`${user}/${old}.jpg`})).resolves.toEqual({path:`${user}/${avatar}.jpg`,cleanupPending:false});expect(c.remove).toHaveBeenCalledWith([`${user}/${old}.jpg`]);});
test('SQ-0703 retries an uncertain authoritative update without deleting a possible current avatar',async()=>{const e=new Error('update');const c=client(e);await expect(replaceAvatar(c.value as never,{userId:user,avatarId:avatar,asset:{uri:'file://a',mimeType:'image/jpeg',byteSize:2,width:10,height:10},previousPath:null})).rejects.toBe(e);expect(c.rpc).toHaveBeenCalledTimes(2);expect(c.remove).not.toHaveBeenCalled();});
test('SQ-0703 removal reports recoverable cleanup',async()=>{const c=client(null,new Error('offline'));await expect(removeAvatar(c.value as never,user,`${user}/${old}.jpg`)).resolves.toEqual({cleanupPending:true});expect(c.rpc).toHaveBeenCalledWith('replace_avatar',{p_expected_path:`${user}/${old}.jpg`});});
test('SQ-0703 signs only an owner path for five minutes',async()=>{const c=client();await expect(getAvatarSignedUrl(c.value as never,user,`${user}/${avatar}.jpg`)).resolves.toBe('https://signed.example/avatar');expect(c.createSignedUrl).toHaveBeenCalledWith(`${user}/${avatar}.jpg`,300);await expect(getAvatarSignedUrl(c.value as never,user,`other/${avatar}.jpg`)).resolves.toBeNull();});
test('SQ-0703 retries stale private avatar cleanup on profile load',async()=>{const c=client();await expect(cleanupStaleAvatars(c.value as never,user)).resolves.toBe(false);expect(c.remove).toHaveBeenCalledWith([`${user}/${old}.jpg`]);expect(c.rpc).toHaveBeenCalledWith('confirm_avatar_cleanup',{p_storage_path:`${user}/${old}.jpg`});});
