import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.generated';
import type { ProofAsset } from '@/features/proof/proof-picker';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validPath(userId:string,path:string){return path.startsWith(`${userId}/`)&&/^[0-9a-f-]+\.jpg$/i.test(path.slice(userId.length+1));}
export async function getAvatarSignedUrl(client:SupabaseClient<Database>,userId:string,path:string|null){if(!path||!uuid.test(userId)||!validPath(userId,path))return null;const signed=await client.storage.from('avatars').createSignedUrl(path,300);if(signed.error)throw signed.error;return signed.data.signedUrl;}
export async function replaceAvatar(client:SupabaseClient<Database>,input:{userId:string;avatarId:string;asset:ProofAsset;previousPath:string|null}){if(!uuid.test(input.userId)||!uuid.test(input.avatarId)||input.asset.mimeType!=='image/jpeg')throw new Error('Invalid avatar input');const path=`${input.userId}/${input.avatarId}.jpg`;const bytes=await(await fetch(input.asset.uri)).arrayBuffer();if(bytes.byteLength!==input.asset.byteSize)throw new Error('Avatar file changed before upload');const bucket=client.storage.from('avatars');const uploaded=await bucket.upload(path,bytes,{contentType:'image/jpeg',upsert:false});if(uploaded.error)throw uploaded.error;const args={p_new_path:path,...(input.previousPath?{p_expected_path:input.previousPath}:{})};let changed=await client.rpc('replace_avatar',args);if(changed.error)changed=await client.rpc('replace_avatar',args);if(changed.error)throw changed.error;const outcome=changed.data as {outcome?:unknown};if(outcome.outcome!=='updated'&&outcome.outcome!=='already_updated')throw new Error('Avatar changed on another device');return{path,cleanupPending:await cleanupStaleAvatars(client,input.userId)};}
export async function removeAvatar(client:SupabaseClient<Database>,userId:string,path:string|null){if(!uuid.test(userId))throw new Error('Invalid avatar owner');const args={...(path?{p_expected_path:path}:{})};let result=await client.rpc('replace_avatar',args);if(result.error)result=await client.rpc('replace_avatar',args);if(result.error)throw result.error;const outcome=result.data as {outcome?:unknown};if(outcome.outcome!=='updated'&&outcome.outcome!=='already_updated')throw new Error('Avatar changed on another device');return{cleanupPending:await cleanupStaleAvatars(client,userId)};}
export async function cleanupStaleAvatars(client:SupabaseClient<Database>,userId:string){if(!uuid.test(userId))return false;const listed=await client.rpc('list_avatar_cleanup');if(listed.error)return true;let pending=false;for(const row of listed.data??[]){if(!validPath(userId,row.storage_path)){pending=true;continue;}const removed=await client.storage.from('avatars').remove([row.storage_path]);if(removed.error){pending=true;continue;}const confirmed=await client.rpc('confirm_avatar_cleanup',{p_storage_path:row.storage_path});if(confirmed.error)pending=true;}return pending;}
