import { uploadAndRegisterProof } from './upload-service';
const user='05020000-0000-4000-8000-000000000001',quest='05020000-0000-4000-8000-000000000002',proof='05020000-0000-4000-8000-000000000003';
function client(uploadError:unknown=null){const upload=jest.fn(async()=>({error:uploadError}));const from=jest.fn(()=>({upload}));const rpc=jest.fn(async()=>({data:{status:'uploaded',outcome:'registered',proof_id:proof,quest_instance_id:quest},error:null}));return {client:{storage:{from},rpc} as never,upload,from,rpc};}
beforeEach(()=>{globalThis.fetch=jest.fn(async()=>({arrayBuffer:async()=>new ArrayBuffer(80)})) as never;});
test('SQ-0502 uploads privately then registers authoritative metadata with progress',async()=>{const c=client();const phases:string[]=[];
 await expect(uploadAndRegisterProof(c.client,{userId:user,questInstanceId:quest,proofId:proof,asset:{uri:'file:///safe.jpg',mimeType:'image/jpeg',byteSize:80,width:2,height:2},onProgress:p=>phases.push(p)})).resolves.toMatchObject({status:'uploaded',proofId:proof});
 const path=`${user}/${quest}/${proof}.jpg`;expect(c.from).toHaveBeenCalledWith('quest-proofs');expect(c.upload).toHaveBeenCalledWith(path,expect.any(ArrayBuffer),{contentType:'image/jpeg',upsert:false});
 expect(c.rpc).toHaveBeenCalledWith('register_quest_proof',{p_proof_id:proof,p_quest_instance_id:quest,p_storage_path:path,p_mime_type:'image/jpeg',p_byte_size:80,p_note:null});expect(phases).toEqual(['reading','uploading','registering']);});
test('SQ-0502 safely retries registration after an already-uploaded object conflict',async()=>{const c=client({statusCode:'409'});await expect(uploadAndRegisterProof(c.client,{userId:user,questInstanceId:quest,proofId:proof,asset:{uri:'file:///safe.jpg',mimeType:'image/jpeg',byteSize:80,width:2,height:2}})).resolves.toMatchObject({status:'uploaded'});expect(c.rpc).toHaveBeenCalled();});
test('SQ-0502 rejects changed local bytes before upload',async()=>{const c=client();await expect(uploadAndRegisterProof(c.client,{userId:user,questInstanceId:quest,proofId:proof,asset:{uri:'file:///safe.jpg',mimeType:'image/jpeg',byteSize:81,width:2,height:2}})).rejects.toThrow('changed');expect(c.upload).not.toHaveBeenCalled();});
