export const developmentCopy = {
  productName: 'SideQuest',
  foundationReady: 'Foundation Ready',
  openRoutingCheck: 'Open routing check',
  routingReady: 'Expo Router Ready',
  returnHome: 'Return home',
  loading: 'Loading SideQuest',
  errorTitle: 'Something went wrong',
  errorDescription: 'Please try again. If this continues, share the reference shown by support.',
  retry: 'Try again',
  authRequired: 'Authentication required',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signOut: 'Sign out',
  onboardingTitle: 'Make SideQuest fit your day', onboardingIntro: 'Choose defaults for your first quests. You can change them later.',
  ageNotice: 'SideQuest is for people aged 18 and over.', saveAndExplore: 'Save and Explore', back: 'Back', retrySave: 'Retry save',
  continue: 'Continue', time: 'Time', budget: 'Budget', mood: 'Mood', distance: 'Distance',
  profileTitle: 'Edit preferences', profileIntro: 'Update your defaults for future quests.', savePreferences: 'Save preferences', preferencesSaved: 'Preferences saved.',
  exploreTitle: 'Find a Quest', exploreIntro: 'Choose what fits your day, then we’ll find one Quest for you.', findQuest: 'Find a Quest', filtersRequired: 'Choose one option in each group before searching.', exploreLoadError: 'Unable to load your filters. Please retry.', searchReady: 'Your filters are ready to search.',
  active: { resumeBannerLabel: 'Active Quest', resumeTitle: 'Continue your Active Quest', resumeAction: 'Resume Active Quest', untitled: 'Active Quest', loading: 'Loading your Active Quest', errorTitle: 'Unable to load Active Quest', restoreError: 'Unable to restore your Active Quest. Please reconnect and try again.', unavailable: 'This Active Quest is no longer available.', emptyTitle: 'No Active Quest', emptyDescription: 'Find and accept a Quest to begin.', backToExplore: 'Back to Explore', offlineTitle: 'You’re offline', offlineDescription: 'Showing the last restored Quest. Reconnect before changing it.', status: 'Active Quest', category: 'Category', duration: 'Duration', minutes: 'minutes', cost: 'Estimated cost', difficulty: 'Difficulty', xp: 'XP', instructions: 'Instructions', safety: 'Safety and physical demands', proof: 'Proof', noProof: 'No proof added yet.', addProof: 'Add proof', complete: 'Complete Quest', proofRequired: 'Add proof before completing this Quest.', abandon: 'Abandon Quest' },
  candidate: { loading: 'Finding a Quest that fits your filters…', errorTitle: 'We couldn’t find your Quest', errorDescription: 'Something went wrong while searching. Please try again.', retry: 'Retry search', noMatchTitle: 'No matching Quest yet', noMatchDescription: 'Try adjusting one filter to discover an eligible Quest.', exhaustedTitle: 'You’ve seen every option', exhaustedDescription: 'Adjust your filters to find another Quest.', expiredTitle: 'This Candidate expired', expiredDescription: 'Candidate Quests are held for 30 minutes. Find another Quest with the same filters.', expiresIn: 'Offer expires in', minute: 'minute', minutes: 'minutes', lessThanMinute: 'less than a minute', mayBeExpired: 'Offer may have expired. Confirm with the server to continue.', category: 'Category', duration: 'Duration', cost: 'Cost', distance: 'Distance', difficulty: 'Difficulty', xp: 'XP', instructions: 'Instructions', safety: 'Safety', accept: 'Accept Quest', reroll: 'Find another', relaxFilters: 'Edit filters', findAnother: 'Find Another Quest' },
  options: {
    flexible: 'Flexible', surprise: 'Surprise me', thirtyMinutes: '30 minutes', oneHour: '1 hour', twoHours: '2 hours', halfDay: 'Half day',
    free: 'Free', under50000: 'Under Rp50.000', under100000: 'Under Rp100.000', walking: 'Walking', under3km: 'Under 3 km', under10km: 'Under 10 km',
    chill: 'Chill', food: 'Food', explore: 'Explore', active: 'Active', creative: 'Creative',
  },
} as const;
