export const developmentCopy = {
  productName: 'SideQuest',
  foundationReady: 'Foundation Ready',
  openRoutingCheck: 'Open routing check',
  routingReady: 'Expo Router Ready',
  returnHome: 'Return home',
  loading: 'Loading SideQuest',
  errorTitle: 'Something went wrong',
  errorDescription: 'Please try again. If this continues, share the reference shown by support.',
  retry: 'Try again',
  authRequired: 'Authentication required',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signOut: 'Sign out',
  onboardingTitle: 'Make SideQuest fit your day', onboardingIntro: 'Choose defaults for your first quests. You can change them later.',
  ageNotice: 'SideQuest is for people aged 18 and over.', saveAndExplore: 'Save and Explore', back: 'Back', retrySave: 'Retry save',
  continue: 'Continue', time: 'Time', budget: 'Budget', mood: 'Mood', distance: 'Distance',
  options: {
    flexible: 'Flexible', surprise: 'Surprise me', thirtyMinutes: '30 minutes', oneHour: '1 hour', twoHours: '2 hours', halfDay: 'Half day',
    free: 'Free', under50000: 'Under Rp50.000', under100000: 'Under Rp100.000', walking: 'Walking', under3km: 'Under 3 km', under10km: 'Under 10 km',
    chill: 'Chill', food: 'Food', explore: 'Explore', active: 'Active', creative: 'Creative',
  },
} as const;
