export const developmentCopy = {
  productName: 'SideQuest',
  foundationReady: 'Foundation Ready',
  openRoutingCheck: 'Open routing check',
  routingReady: 'Expo Router Ready',
  returnHome: 'Return home',
  loading: 'Loading SideQuest',
  errorTitle: 'Something went wrong',
  errorDescription: 'Please try again. If this continues, share the reference shown by support.',
  retry: 'Try again',
  authRequired: 'Authentication required',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signOut: 'Sign out',
} as const;
