export const showcaseCopy = {
  pageTitle: 'Field kit',
  pageDescription:
    'Development-only reference for SideQuest color, type, controls, and common states.',
  back: 'Back to foundation',
  themeTitle: 'Theme',
  themeDescription: 'System follows the current device appearance.',
  themeOptions: {
    system: 'System',
    light: 'Light',
    dark: 'Dark',
  },
  colorsTitle: 'Semantic colors',
  colorLabels: {
    primary: 'Primary',
    accent: 'Accent',
    success: 'Success',
    warning: 'Warning',
    danger: 'Danger',
  },
  typographyTitle: 'Typography',
  typographySamples: {
    display: 'Go somewhere new.',
    heading: 'A capable field companion',
    title: 'One clear objective',
    body: 'Designed for quick decisions and real-world movement.',
    bodySmall: 'Supporting detail stays readable at a glance.',
    label: 'ACTION LABEL',
    caption: 'Useful context, never tiny trivia.',
  },
  buttonsTitle: 'Buttons',
  buttons: {
    primary: 'Primary action',
    secondary: 'Secondary action',
    ghost: 'Ghost action',
    danger: 'Danger action',
    disabled: 'Unavailable',
    loading: 'Preparing',
  },
  chipsTitle: 'Chips',
  chips: {
    default: 'Chill',
    selected: 'Explore',
    disabled: 'Unavailable',
  },
  inputsTitle: 'Inputs',
  inputs: {
    label: 'Display name',
    placeholder: 'How should SideQuest address you?',
    helper: 'Use a name between 2 and 40 characters.',
    error: 'Enter at least 2 characters.',
    disabledLabel: 'Locked field',
    disabledValue: 'Unavailable during this demo',
  },
  cardsTitle: 'Cards',
  cards: {
    defaultTitle: 'Default card',
    defaultBody: 'Crisp separation for grouped information.',
    elevatedTitle: 'Elevated card',
    elevatedBody: 'Reserved for content that needs a little more presence.',
    interactiveTitle: 'Interactive card',
    interactiveBody: 'A whole-card action with a clear accessibility label.',
  },
  statesTitle: 'Application states',
  states: {
    loading: 'Checking the trail…',
    emptyTitle: 'Nothing here yet',
    emptyBody: 'When content arrives, it will appear in this space.',
    errorTitle: 'Could not load this section',
    errorBody: 'Check your connection and try once more.',
    retry: 'Try again',
  },
} as const;
