-- SQ-0004: identity, preferences, category/location catalog, and immutable
-- Quest Template version foundations. No seed rows or RLS policies belong here.

create type public.difficulty as enum ('easy', 'medium', 'hard');
create type public.location_mode as enum ('none', 'area', 'place');

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create function public.protect_quest_template_content()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (to_jsonb(new) - array['moderation_status', 'priority', 'enabled_at', 'disabled_at', 'updated_at'])
     is distinct from
     (to_jsonb(old) - array['moderation_status', 'priority', 'enabled_at', 'disabled_at', 'updated_at']) then
    raise exception 'Quest Template content is immutable; create a new version row';
  end if;

  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Shared timestamp trigger for mutable SQ-0004 records.';

create table public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  avatar_path text,
  onboarding_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_check
    check (display_name = btrim(display_name) and char_length(display_name) between 2 and 40),
  constraint profiles_avatar_path_check
    check (avatar_path is null or (avatar_path = btrim(avatar_path) and avatar_path <> ''))
);

create table public.user_preferences (
  user_id uuid primary key references public.profiles (user_id) on delete cascade,
  default_time text not null,
  default_budget text not null,
  default_mood text not null,
  default_distance text not null,
  theme text not null default 'system',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_default_time_check
    check (default_time in ('30_minutes', '1_hour', '2_hours', 'half_day')),
  constraint user_preferences_default_budget_check
    check (default_budget in ('free', 'under_50000', 'under_100000', 'flexible')),
  constraint user_preferences_default_mood_check
    check (default_mood in ('chill', 'food', 'explore', 'active', 'creative', 'random')),
  constraint user_preferences_default_distance_check
    check (default_distance in ('walking', 'under_3_km', 'under_10_km', 'flexible')),
  constraint user_preferences_theme_check
    check (theme in ('system', 'light', 'dark'))
);

create table public.categories (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name_key text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_slug_check
    check (slug in ('chill', 'food', 'explore', 'active', 'creative')),
  constraint categories_name_key_check
    check (name_key = btrim(name_key) and name_key <> '')
);

comment on table public.categories is
  'Quest Category authority. SQ-0006 seeds the five allowed slugs; random is never a category.';

create table public.locations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  area_code text not null,
  latitude double precision,
  longitude double precision,
  address text,
  external_map_url text,
  timezone text not null,
  availability_json jsonb,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locations_name_check check (name = btrim(name) and name <> ''),
  constraint locations_area_code_check check (area_code = btrim(area_code) and area_code <> ''),
  constraint locations_coordinates_pair_check check ((latitude is null) = (longitude is null)),
  constraint locations_latitude_check check (latitude is null or latitude between -90 and 90),
  constraint locations_longitude_check check (longitude is null or longitude between -180 and 180),
  constraint locations_external_map_url_check
    check (external_map_url is null or external_map_url ~ '^https://[^[:space:]]+$'),
  constraint locations_timezone_check check (timezone = btrim(timezone) and timezone <> ''),
  constraint locations_availability_check
    check (availability_json is null or jsonb_typeof(availability_json) = 'object')
);

create table public.quest_templates (
  id uuid primary key default gen_random_uuid(),
  template_family_id uuid not null,
  version integer not null,
  category_id smallint not null references public.categories (id) on delete restrict,
  title text not null,
  description text not null,
  instructions jsonb not null,
  duration_min integer not null,
  duration_max integer not null,
  estimated_cost_min integer not null default 0,
  estimated_cost_max integer not null default 0,
  currency_code char(3) not null,
  difficulty public.difficulty not null,
  base_xp integer not null,
  location_mode public.location_mode not null,
  area_codes text[],
  location_id uuid references public.locations (id) on delete restrict,
  physical_demand text not null,
  safety_notes text not null,
  availability_json jsonb,
  moderation_status text not null,
  priority smallint not null default 0,
  enabled_at timestamptz,
  disabled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quest_templates_family_version_key unique (template_family_id, version),
  constraint quest_templates_version_check check (version >= 1),
  constraint quest_templates_title_check check (title = btrim(title) and title <> ''),
  constraint quest_templates_description_check check (description = btrim(description) and description <> ''),
  constraint quest_templates_instructions_check
    check (
      jsonb_typeof(instructions) = 'array'
      and jsonb_array_length(instructions) between 1 and 10
      and not jsonb_path_exists(instructions, '$[*] ? (@.type() != "string")')
    ),
  constraint quest_templates_duration_check
    check (duration_min between 1 and 480 and duration_max between 1 and 480 and duration_min <= duration_max),
  constraint quest_templates_cost_check
    check (estimated_cost_min >= 0 and estimated_cost_min <= estimated_cost_max),
  constraint quest_templates_currency_check check (currency_code = 'IDR'),
  constraint quest_templates_base_xp_check check (base_xp between 50 and 200),
  constraint quest_templates_location_check
    check (
      (location_mode = 'place' and location_id is not null)
      or (location_mode <> 'place' and location_id is null)
    ),
  constraint quest_templates_area_codes_check
    check (area_codes is null or cardinality(area_codes) > 0),
  constraint quest_templates_physical_demand_check
    check (physical_demand = btrim(physical_demand) and physical_demand <> ''),
  constraint quest_templates_safety_notes_check
    check (safety_notes = btrim(safety_notes) and safety_notes <> ''),
  constraint quest_templates_availability_check
    check (availability_json is null or jsonb_typeof(availability_json) = 'object'),
  constraint quest_templates_moderation_status_check
    check (moderation_status in ('approved', 'draft', 'disabled')),
  constraint quest_templates_enablement_check
    check (disabled_at is null or enabled_at is null or disabled_at >= enabled_at)
);

comment on table public.quest_templates is
  'Each content version is a new row. id identifies the exact immutable version referenced by an Instance.';

create index locations_area_enabled_idx
  on public.locations (area_code, is_enabled);

create index quest_templates_eligibility_idx
  on public.quest_templates (moderation_status, category_id, enabled_at)
  where disabled_at is null;

create index quest_templates_location_idx
  on public.quest_templates (location_id)
  where location_id is not null;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger locations_set_updated_at
before update on public.locations
for each row execute function public.set_updated_at();

create trigger quest_templates_set_updated_at
before update on public.quest_templates
for each row execute function public.set_updated_at();

create trigger quest_templates_protect_content
before update on public.quest_templates
for each row execute function public.protect_quest_template_content();
